name: Build, test and analyst

on:
  push:
    branches: ["main"]
    paths:
      - lib/**
      - web/**
      - main.dart
      - .github/**

  pull_request:
    branches: ["main"]
    paths:
      - lib/**
      - web/**
      - main.dart
      - .github/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "flutter"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  build:
    name: Build and run tests
    environment:
      name: Flutter Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Run unit test
        run: flutter test
      - name: Build for web
        run: flutter build web
      - name: Analyst code
        run: |
          flutter pub add coverage codecov
          flutter pub run codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}